import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This maintains the automatic folder-to-menu logic
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.' // This scans everything in /docs
    }
  ],
};

export default sidebars;